stages:
  - test
  - build
  - deploy

default:
  image: node:18
  before_script:
    - npm config set cache $NPM_CACHE_DIR
    - npm ci --verbose --cache $NPM_CACHE_DIR --prefer-offline
  cache:
    key: $CI_COMMIT_REF_SLUG
    paths:
      - .npm/

variables:
  NPM_CACHE_DIR: "$CI_PROJECT_DIR/.npm"
  GITLAB_ENV: develop

workflow:
  rules:
    - if: $CI_COMMIT_REF_NAME == "main"
      variables:
        GITLAB_ENV: prod
      when: always
    - if: $CI_COMMIT_REF_NAME == "develop"
      variables:
        GITLAB_ENV: develop
      when: always
    - if: '$CI_COMMIT_BRANCH =~ /^feature\/.*$/ && $CI_MERGE_REQUEST_ID == null'
      when: always
      variables:
        GITLAB_ENV: develop
    - when: never

test:
  stage: test
  rules:
    - if: '$CI_COMMIT_BRANCH =~ /^feature\/.*$/ && $CI_MERGE_REQUEST_ID == null'
      when: always
  script:
    - echo test

build_frontend:
  stage: build
  script:
    - npm run build
    - echo "Build completed."
  artifacts:
    paths:
      - build/


deploy_to_s3:
  before_script:
    - >
      export $(printf "AWS_ACCESS_KEY_ID=%s AWS_SECRET_ACCESS_KEY=%s AWS_SESSION_TOKEN=%s"
      $(aws sts assume-role-with-web-identity
      --role-arn ${ROLE_ARN}
      --role-session-name "GitLabRunner-${CI_PROJECT_ID}-${CI_PIPELINE_ID}"
      --web-identity-token ${GITLAB_OIDC_TOKEN}
      --duration-seconds 3600
      --query 'Credentials.[AccessKeyId,SecretAccessKey,SessionToken]'
      --output text))
  stage: deploy
  image:
    name: amazon/aws-cli:latest
    entrypoint: [ "" ]
  id_tokens:
    GITLAB_OIDC_TOKEN:
      aud: https://gitlab.com/devops01ua
  script:
    - aws s3 sync build/ $FRONTEND_BUCKET
    - ./aws/scripts/invalidation.sh $DISTRIBUTION_ID
  environment:
    name: $GITLAB_ENV
    url: ${CLOUDFRONT_URL}

services:
  - docker:dind

sonarqube-check:
  stage: sonar-scanner
  before_script:
    - export SONAR_HOST_URL=$SONAR_URL
  image:
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: [""]
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"  # Defines the location of the analysis task cache
    GIT_DEPTH: "0"  # Tells git to fetch all the branches of the project, required by the analysis task
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    - sonar-scanner -X
  allow_failure: true
  only:
    - develop
    - main
  tags:
    - devops01


